# Generated by Django 5.1.4 on 2025-01-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following_comment_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
