# Generated by Django 5.1.4 on 2025-01-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_thread_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='title',
        ),
    ]
